name: Nasanow


on: push


jobs:
  insta:
    name: APOD
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        
      - name: Keep this repo alive
        uses: gautamkrishnar/keepalive-workflow@master

      - name: Set up Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache Python packages 💾
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install packages ⚙
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Use HEREDOC for `run` to escape possible single and double quotes in the message.
      - name: insta APOD 🐦📷
        env:

                  API_KEY: ${{ secrets.API_KEY }}

                  USERNAME: ${{ secrets.USERNAME }}

                  PASSWORD: ${{ secrets.PASSWORD }}

                  TELE_USER: ${{ secrets.TELE_USER }}

                  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

                  GOOGLE_API_KEY:  ${{ secrets.GOOGLE_API_KEY }}

                  OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
                  
        run: python instasa.py

      - name: Atualizar arquivo de legenda
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git add legendas_postadas.txt
          git commit -m "Atualizar arquivo de legenda [skip ci]"  # Ignorar a execução do workflow para este commit
          git push
